'use strict';Object.defineProperty(exports,"__esModule",{value:true});var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();var _react=require('react');var _react2=_interopRequireDefault(_react);var _propTypes=require('prop-types');var _propTypes2=_interopRequireDefault(_propTypes);var _reactRedux=require('react-redux');var _shinkansenSignals=require('shinkansen-signals');var _embark=require('../../../actions/stages/embark');var EmbarkStageActions=_interopRequireWildcard(_embark);var _components=require('../../../components');var _embark2=require('../../../transformers/stages/embark');var _stages=require('../../../components/stages');function _interopRequireWildcard(obj){if(obj&&obj.__esModule){return obj;}else{var newObj={};if(obj!=null){for(var key in obj){if(Object.prototype.hasOwnProperty.call(obj,key))newObj[key]=obj[key];}}newObj.default=obj;return newObj;}}function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return call&&(typeof call==="object"||typeof call==="function")?call:self;}function _inherits(subClass,superClass){if(typeof superClass!=="function"&&superClass!==null){throw new TypeError("Super expression must either be null or a function, not "+typeof superClass);}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass;}// eslint-disable-line no-unused-vars
var EMBARK=_shinkansenSignals.Signals.EMBARK;var EmbarkStagePage=function(_React$Component){_inherits(EmbarkStagePage,_React$Component);function EmbarkStagePage(){var _ref;var _temp,_this,_ret;_classCallCheck(this,EmbarkStagePage);for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key];}return _ret=(_temp=(_this=_possibleConstructorReturn(this,(_ref=EmbarkStagePage.__proto__||Object.getPrototypeOf(EmbarkStagePage)).call.apply(_ref,[this].concat(args))),_this),_this.onSubmit=function(response){var dispatch=_this.props.dispatch;/**
     *  Dispatch and notify the Node App via Axios
     */dispatch(EmbarkStageActions.store(response));},_temp),_possibleConstructorReturn(_this,_ret);}_createClass(EmbarkStagePage,[{key:'componentDidMount',/**
   *  List routes
   */value:function componentDidMount(){// console.log('(EmbarkStagePage)componentDidMount()') // eslint-disable-line
var dispatch=this.props.dispatch;/**
     *  Dispatch and notify the Node App via Axios
     */dispatch(EmbarkStageActions.fetch());}},{key:'render',value:function render(){// console.log('(EmbarkStagePage)render()') // eslint-disable-line
var embark=this.props.embark;return _react2.default.createElement('section',null,_react2.default.createElement('header',null,_react2.default.createElement('h1',null,'Embark Route')),_react2.default.createElement(_stages.EmbarkStage,{onSubmit:this.onSubmit,embark:embark}),_react2.default.createElement(_components.Navigation,null));}}]);return EmbarkStagePage;}(_react2.default.Component);EmbarkStagePage.propTypes={params:_propTypes2.default.object.isRequired,dispatch:_propTypes2.default.func.isRequired,embark:_propTypes2.default.shape({status:_propTypes2.default.number.isRequired,definition:_propTypes2.default.object})};exports.default=(0,_reactRedux.connect)(function(_ref2){var _ref2$EMBARK=_ref2[EMBARK],embark=_ref2$EMBARK===undefined?{}:_ref2$EMBARK;return{embark:(0,_embark2.transform)(embark)};})(EmbarkStagePage);