version: 2.1

jobs:
  publish:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            set -e

            NAME=$(node -p "require('./package.json').name")
            VERSION=$(node -p "require('./package.json').version")
            PUBLISHED_VERSION=$(npm view $NAME version)

            if [ "$VERSION" != "$PUBLISHED_VERSION" ]
            then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm install
              npm publish
            fi

workflows:
  version: 2
  commit-workflow:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
