'use strict';Object.defineProperty(exports,"__esModule",{value:true});var _getPrototypeOf=require('babel-runtime/core-js/object/get-prototype-of');var _getPrototypeOf2=_interopRequireDefault(_getPrototypeOf);var _classCallCheck2=require('babel-runtime/helpers/classCallCheck');var _classCallCheck3=_interopRequireDefault(_classCallCheck2);var _createClass2=require('babel-runtime/helpers/createClass');var _createClass3=_interopRequireDefault(_createClass2);var _possibleConstructorReturn2=require('babel-runtime/helpers/possibleConstructorReturn');var _possibleConstructorReturn3=_interopRequireDefault(_possibleConstructorReturn2);var _inherits2=require('babel-runtime/helpers/inherits');var _inherits3=_interopRequireDefault(_inherits2);var _react=require('react');var _react2=_interopRequireDefault(_react);var _propTypes=require('prop-types');var _propTypes2=_interopRequireDefault(_propTypes);var _reactRedux=require('react-redux');var _shinkansenSignals=require('shinkansen-signals');var _debarkStage=require('../../../actions/stages/debark-stage');var DebarkStageActions=_interopRequireWildcard(_debarkStage);var _components=require('../../../components');var _stages=require('../../../components/stages');function _interopRequireWildcard(obj){if(obj&&obj.__esModule){return obj;}else{var newObj={};if(obj!=null){for(var key in obj){if(Object.prototype.hasOwnProperty.call(obj,key))newObj[key]=obj[key];}}newObj.default=obj;return newObj;}}function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}// eslint-disable-line no-unused-vars
var DEBARK=_shinkansenSignals.Signals.DEBARK;var DebarkStagePage=function(_React$Component){(0,_inherits3.default)(DebarkStagePage,_React$Component);function DebarkStagePage(){var _ref;var _temp,_this,_ret;(0,_classCallCheck3.default)(this,DebarkStagePage);for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key];}return _ret=(_temp=(_this=(0,_possibleConstructorReturn3.default)(this,(_ref=DebarkStagePage.__proto__||(0,_getPrototypeOf2.default)(DebarkStagePage)).call.apply(_ref,[this].concat(args))),_this),_this.onSubmit=function(response){var dispatch=_this.props.dispatch;/**
     *  Dispatch and notify the Node App via Axios
     */dispatch(DebarkStageActions.store(response));},_temp),(0,_possibleConstructorReturn3.default)(_this,_ret);}(0,_createClass3.default)(DebarkStagePage,[{key:'componentDidMount',/**
   *  Halt routes
   */value:function componentDidMount(){// console.log('(DebarkStagePage)componentDidMount()') // eslint-disable-line
var dispatch=this.props.dispatch;/**
     *  Dispatch and notify the Node App via Axios
     */dispatch(DebarkStageActions.fetch());}},{key:'render',value:function render(){// console.log('(DebarkStagePage)render()') // eslint-disable-line
var debark=this.props.debark;return _react2.default.createElement('section',null,_react2.default.createElement('header',null,_react2.default.createElement('h1',null,'Debark Route')),_react2.default.createElement(_stages.DebarkStage,{onSubmit:this.onSubmit,debark:debark}),_react2.default.createElement(_components.Navigation,null));}}]);return DebarkStagePage;}(_react2.default.Component);DebarkStagePage.propTypes={params:_propTypes2.default.object.isRequired,dispatch:_propTypes2.default.func.isRequired,debark:_propTypes2.default.shape({status:_propTypes2.default.number.isRequired,definition:_propTypes2.default.object})};exports.default=(0,_reactRedux.connect)(function(_ref2){var debark=_ref2[DEBARK];return{debark:debark};})(DebarkStagePage);