'use strict';Object.defineProperty(exports,"__esModule",{value:true});var _getPrototypeOf=require('babel-runtime/core-js/object/get-prototype-of');var _getPrototypeOf2=_interopRequireDefault(_getPrototypeOf);var _classCallCheck2=require('babel-runtime/helpers/classCallCheck');var _classCallCheck3=_interopRequireDefault(_classCallCheck2);var _createClass2=require('babel-runtime/helpers/createClass');var _createClass3=_interopRequireDefault(_createClass2);var _possibleConstructorReturn2=require('babel-runtime/helpers/possibleConstructorReturn');var _possibleConstructorReturn3=_interopRequireDefault(_possibleConstructorReturn2);var _inherits2=require('babel-runtime/helpers/inherits');var _inherits3=_interopRequireDefault(_inherits2);var _react=require('react');var _react2=_interopRequireDefault(_react);var _propTypes=require('prop-types');var _propTypes2=_interopRequireDefault(_propTypes);var _reactRedux=require('react-redux');var _shinkansenSignals=require('shinkansen-signals');var _embarkStage=require('../../../actions/stages/embark-stage');var EmbarkStageActions=_interopRequireWildcard(_embarkStage);var _components=require('../../../components');var _stages=require('../../../components/stages');function _interopRequireWildcard(obj){if(obj&&obj.__esModule){return obj;}else{var newObj={};if(obj!=null){for(var key in obj){if(Object.prototype.hasOwnProperty.call(obj,key))newObj[key]=obj[key];}}newObj.default=obj;return newObj;}}function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}// eslint-disable-line no-unused-vars
var EMBARK=_shinkansenSignals.Signals.EMBARK;var EmbarkStagePage=function(_React$Component){(0,_inherits3.default)(EmbarkStagePage,_React$Component);function EmbarkStagePage(){var _ref;var _temp,_this,_ret;(0,_classCallCheck3.default)(this,EmbarkStagePage);for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key];}return _ret=(_temp=(_this=(0,_possibleConstructorReturn3.default)(this,(_ref=EmbarkStagePage.__proto__||(0,_getPrototypeOf2.default)(EmbarkStagePage)).call.apply(_ref,[this].concat(args))),_this),_this.onSubmit=function(response){var dispatch=_this.props.dispatch;/**
     *  Dispatch and notify the Node App via Axios
     */dispatch(EmbarkStageActions.store(response));},_temp),(0,_possibleConstructorReturn3.default)(_this,_ret);}(0,_createClass3.default)(EmbarkStagePage,[{key:'componentDidMount',/**
   *  List routes
   */value:function componentDidMount(){// console.log('(EmbarkStagePage)componentDidMount()') // eslint-disable-line
var dispatch=this.props.dispatch;/**
     *  Dispatch and notify the Node App via Axios
     */dispatch(EmbarkStageActions.fetch());}},{key:'render',value:function render(){// console.log('(EmbarkStagePage)render()') // eslint-disable-line
var embark=this.props.embark;return _react2.default.createElement('section',null,_react2.default.createElement('header',null,_react2.default.createElement('h1',null,'Embark Route')),_react2.default.createElement(_stages.EmbarkStage,{onSubmit:this.onSubmit,embark:embark}),_react2.default.createElement(_components.Navigation,null));}}]);return EmbarkStagePage;}(_react2.default.Component);EmbarkStagePage.propTypes={params:_propTypes2.default.object.isRequired,dispatch:_propTypes2.default.func.isRequired,embark:_propTypes2.default.shape({status:_propTypes2.default.number.isRequired,definition:_propTypes2.default.object})};exports.default=(0,_reactRedux.connect)(function(_ref2){var embark=_ref2[EMBARK];return{embark:embark};})(EmbarkStagePage);