#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

has_package_dependencies_changes () {
  git diff HEAD~1..HEAD~0 -- origin/main package.json | grep \
    -e '+\s*\"@modernpoacher/isomorphic\":\s\".*"' \
    -e '+\s*\"shinkansen-engine\":\s\".*"'
}

if has_package_dependencies_changes;
then
  npx cross-env DEBUG=@modernpoacher/hooks* node .husky/post-commit.mjs
fi
