#!/bin/sh

get_package_dependencies_changes () {
  local CURRENT_BRANCH
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  git diff HEAD~1..HEAD~0 -- "origin/$CURRENT_BRANCH" package.json | grep \
    -e '+\s*\"@modernpoacher/isomorphic\":\s\".*"' \
    -e '+\s*\"shinkansen-engine\":\s\".*"'
}

has_package_dependencies_changes () {
  [ ! -z "$(get_package_dependencies_changes)" ]
}

if has_package_dependencies_changes;
then
  npx cross-env DEBUG=@modernpoacher/hooks* node .husky/post-commit.mjs
fi
